#!/bin/bash
# Инструкция для загрузки base_bot_update.zip на VPS

echo "🚀 Загрузка Base Bot Update на VPS"
echo "=================================="

# Получаем внешний IP (замените на ваш реальный IP)
YOUR_LOCAL_IP=$(curl -s ifconfig.me 2>/dev/null || echo "YOUR_LOCAL_IP_HERE")

echo "📡 Ваш внешний IP: $YOUR_LOCAL_IP"
echo ""
echo "📋 Инструкции для VPS:"
echo "======================"
echo ""
echo "1. На VPS выполните команду:"
echo "   cd /root/pancake-bot"
echo ""
echo "2. Загрузите файл:"
echo "   wget http://$YOUR_LOCAL_IP:8080/base_bot_update.zip"
echo ""
echo "3. Распакуйте файл:"
echo "   unzip base_bot_update.zip"
echo ""
echo "4. Создайте резервную копию:"
echo "   cp main_base.py main_base.py.backup"
echo ""
echo "5. Замените файл:"
echo "   cp base_bot_update/main_base.py ./"
echo ""
echo "6. Проверьте синтаксис:"
echo "   python3 -m py_compile main_base.py"
echo ""
echo "7. Перезапустите бота:"
echo "   systemctl restart base-bot"
echo ""
echo "8. Проверьте статус:"
echo "   systemctl status base-bot"
echo ""
echo "⚠️  ВАЖНО: После загрузки остановите локальный сервер!"
echo "   Нажмите Ctrl+C в терминале где запущен сервер"
echo ""
echo "🔍 Если что-то пойдет не так:"
echo "   cp main_base.py.backup main_base.py"
echo "   systemctl restart base-bot"
